### ISSUE TITLE
Receptionist Checklist

### ISSUE THREAD

**Issue by Zayood** [SeoFernando25/dcms-g6#34]
As a receptionist I can:

- [x] Add patient Information
- [x] Edit patient Information
- [x] Set patient appointments

**Comment by HenryChen666** [comment]
done
