### ISSUE TITLE
Patient Checklist

### ISSUE THREAD

**Issue by Zayood** [SeoFernando25/dcms-g6#36]
As a patient I want to be able to:

- [x] Access my records
- [ ] Access my medical history
- [ ] Access my upcoming appointments
- [x] Scheduling an appointment
